#ifndef UI_WTD_H
#define UI_WTD_H

// Autogenerated on: 06-06-2017 02:06:38 
#include <Wt/WFileResource>
#include <Wt/WContainerWidget>
#include <Wt/WPushButton>
#include <Wt/WText>
#include <Wt/WBootstrapTheme>

class Ui_WtD
{

public:

	Wt::WContainerWidget *wt_root;
	Wt::WPushButton *button;
	Wt::WText *text;

	void setupUi(Wt::WContainerWidget *PageRoot)
	{

		Wt::WBootstrapTheme * p_wtTheme = new Wt::WBootstrapTheme();
		p_wtTheme->setVersion(Wt::WBootstrapTheme::Version3);
		Wt::WApplication::instance()->setTheme(p_wtTheme);
		Wt::WApplication::instance()->setTitle("Untitled Wt Webapp");

		addAllStyleSheets();

		wt_root = (PageRoot);
		wt_root->setId("wt_root");
		wt_root->setStyleClass(Wt::WString::fromUTF8(""));
		wt_root->setInline(0);
		{
			button = new Wt::WPushButton(wt_root);
			button->setId("button");
			button->setStyleClass(Wt::WString::fromUTF8("btn-default btn with-label btn btn-default with-label"));
			button->setInline(1);
			button->setEmptyText(Wt::WString::fromUTF8(""));
			button->setText(Wt::WString::fromUTF8("Click Me"));
			button->setLink(Wt::WLink(""));
			text = new Wt::WText(wt_root);
			text->setId("text");
			text->setStyleClass(Wt::WString::fromUTF8("hidden"));
			text->setInline(1);
			text->setTextFormat((Wt::TextFormat)0);
			text->setText(Wt::WString::fromUTF8("Hello World"));
		}

		connectAllSignals();

		addAllJavaScripts();

	}


	void addAllStyleSheets()
	{

		Wt::WApplication::instance()->useStyleSheet(Wt::WLink("resources/main.css"));

	}


	void addAllJavaScripts()
	{


	}


	void connectAllSignals()
	{

		button->clicked().connect(std::bind([=]() { text->toggleStyleClass ("hidden", !text->hasStyleClass("hidden")); }));

	}


};

#endif // UI_WTD_H